import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, ActivityIndicator } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '../../theme/colors';
import api from '../../api/api';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const BADGE_STYLES = {
  pink: { bg: colors.lightPink, color: colors.pink },
  purple: { bg: colors.lavender, color: colors.purple },
  amber: { bg: colors.amberBg, color: '#b8600a' },
};

function buildReportHTML({ period, stats, topFoods, symptoms, nextWeekTip, userName }) {
  const todayStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const foodRows = topFoods.length > 0
    ? topFoods.map(f => `
        <tr>
          <td style="padding:8px 0; font-size:13px; color:#1a1a2e;">${f.name}</td>
          <td style="padding:8px 0; text-align:right; font-size:13px; color:#9B4DB5; font-weight:700;">${f.freq}×</td>
        </tr>`).join('')
    : `<tr><td colspan="2" style="padding:8px 0; font-size:12px; color:#888;">No food data logged yet</td></tr>`;

  const symptomChips = symptoms.length > 0
    ? symptoms.map(s => `<span style="display:inline-block; background:#FDE8F0; color:#E5457A; padding:5px 12px; border-radius:99px; font-size:11px; font-weight:700; margin:3px;">${s.label}</span>`).join('')
    : `<span style="font-size:12px; color:#888;">No symptoms logged</span>`;

  return `
  <html>
  <head><meta charset="utf-8" /></head>
  <body style="font-family: -apple-system, Helvetica, Arial, sans-serif; margin:0; padding:0; background:#fff;">
    <div style="background:linear-gradient(135deg,#E5457A,#9B4DB5); padding:32px 24px; color:#fff;">
      <h1 style="margin:0; font-size:22px;">🌸 Cycle Ella Health Report</h1>
      <p style="margin:6px 0 0; font-size:13px; opacity:0.9;">${period} Report · ${userName || 'User'} · Generated ${todayStr}</p>
    </div>

    <div style="padding:24px;">
      <h2 style="font-size:13px; text-transform:uppercase; letter-spacing:1px; color:#9B4DB5; margin-bottom:12px;">Summary</h2>
      <table style="width:100%; border-collapse:collapse; margin-bottom:24px;">
        <tr>
          <td style="width:50%; padding:12px; background:#F7F0FC; border-radius:12px;">
            <div style="font-size:22px; font-weight:900; color:#1a1a2e;">${stats.daysLogged}</div>
            <div style="font-size:11px; color:#777;">Days logged</div>
          </td>
          <td style="width:8px;"></td>
          <td style="width:50%; padding:12px; background:#F7F0FC; border-radius:12px;">
            <div style="font-size:22px; font-weight:900; color:#1a1a2e;">${stats.avgCalories}</div>
            <div style="font-size:11px; color:#777;">Avg. daily kcal</div>
          </td>
        </tr>
        <tr><td colspan="3" style="height:8px;"></td></tr>
        <tr>
          <td style="padding:12px; background:#F7F0FC; border-radius:12px;">
            <div style="font-size:22px; font-weight:900; color:#1a1a2e;">${stats.cycleLength}</div>
            <div style="font-size:11px; color:#777;">Cycle length</div>
          </td>
          <td></td>
          <td style="padding:12px; background:#F7F0FC; border-radius:12px;">
            <div style="font-size:22px; font-weight:900; color:#1a1a2e;">${stats.healthScore}</div>
            <div style="font-size:11px; color:#777;">Health score</div>
          </td>
        </tr>
      </table>

      <h2 style="font-size:13px; text-transform:uppercase; letter-spacing:1px; color:#9B4DB5; margin-bottom:12px;">Most Eaten Foods</h2>
      <table style="width:100%; border-collapse:collapse; margin-bottom:24px; border-top:1px solid #eee;">
        ${foodRows}
      </table>

      <h2 style="font-size:13px; text-transform:uppercase; letter-spacing:1px; color:#9B4DB5; margin-bottom:12px;">Symptoms This ${period}</h2>
      <div style="margin-bottom:24px;">${symptomChips}</div>

      <h2 style="font-size:13px; text-transform:uppercase; letter-spacing:1px; color:#9B4DB5; margin-bottom:12px;">Next ${period === 'Weekly' ? 'Week' : 'Month'} Tip</h2>
      <p style="font-size:13px; color:#1a1a2e; line-height:20px; background:#F7F0FC; padding:14px; border-radius:12px;">${nextWeekTip}</p>

      <p style="margin-top:32px; font-size:10px; color:#aaa; text-align:center;">
        Generated by Cycle Ella — AI-powered PCOS nutrition coaching app 🌸<br/>
        This report is for personal tracking purposes only and does not replace medical advice.
      </p>
    </div>
  </body>
  </html>`;
}

export default function ReportsScreen({ navigation }) {
  const [period, setPeriod] = useState('Weekly');
  const [stats, setStats] = useState({ daysLogged: '0/7', avgCalories: '0', cycleLength: '—', healthScore: '0' });
  const [topFoods, setTopFoods] = useState([]);
  const [symptoms, setSymptoms] = useState([]);
  const [nextWeekTip, setNextWeekTip] = useState('Loading your personalized tip...');
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const res = period === 'Weekly'
          ? await api.get('/reports/weekly')
          : await api.get('/reports/monthly');
        if (res.data) {
          if (res.data.stats) setStats(res.data.stats);
          if (res.data.topFoods) setTopFoods(res.data.topFoods);
          if (res.data.symptoms) setSymptoms(res.data.symptoms);
          if (res.data.nextWeekTip) setNextWeekTip(res.data.nextWeekTip);
        }
      } catch (_) {}
    };
    load();
  }, [period]);

  const generatePDF = async () => {
    setExporting(true);
    try {
      const html = buildReportHTML({ period, stats, topFoods, symptoms, nextWeekTip });
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      return uri;
    } catch (err) {
      Alert.alert('Error', 'Could not generate PDF report.');
      return null;
    } finally {
      setExporting(false);
    }
  };

  const handleDownload = async () => {
    const uri = await generatePDF();
    if (!uri) return;
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Save your Cycle Ella Report',
        UTI: 'com.adobe.pdf',
      });
    } else {
      Alert.alert('Saved! 🌸', `PDF saved at: ${uri}`);
    }
  };

  const handleShare = async () => {
    const uri = await generatePDF();
    if (!uri) return;
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Share your Cycle Ella Report',
      });
    } else {
      Alert.alert('Sharing not available', 'Sharing is not supported on this device.');
    }
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.bg }} edges={['top']}>
      <View style={s.header}>
        <TouchableOpacity style={s.backBtn} onPress={() => navigation.goBack()}>
          <Text style={s.backArrow}>‹</Text>
        </TouchableOpacity>
        <Text style={s.headerTitle}>Reports</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
        <View style={s.tabToggle}>
          {['Weekly', 'Monthly'].map(t => (
            <TouchableOpacity key={t} style={[s.tabBtn, period === t && s.tabBtnActive]} onPress={() => setPeriod(t)}>
              <Text style={[s.tabTxt, period === t && s.tabTxtActive]}>{t}</Text>
            </TouchableOpacity>
          ))}
        </View>

        <View style={s.statGrid}>
          {[
            { val: stats.daysLogged, label: 'Days logged' },
            { val: stats.avgCalories, label: 'Avg. daily kcal' },
            { val: stats.cycleLength, label: 'Cycle length' },
            { val: stats.healthScore, label: 'Health score' },
          ].map((stat, i) => (
            <View key={i} style={s.statCell}>
              <Text style={s.statVal}>{stat.val}</Text>
              <Text style={s.statLabel}>{stat.label}</Text>
            </View>
          ))}
        </View>

        <View style={s.card}>
          <Text style={s.cardTitle}>Most Eaten Foods</Text>
          {topFoods.length === 0 ? (
            <Text style={s.emptyTxt}>No food logged yet this {period.toLowerCase()}</Text>
          ) : topFoods.map((food, i) => (
            <View key={i} style={s.foodRow}>
              <Text style={{ fontSize: 22 }}>{food.emoji}</Text>
              <View style={{ flex: 1, gap: 4 }}>
                <Text style={s.foodName}>{food.name}</Text>
                <View style={s.foodBarTrack}>
                  <LinearGradient colors={['#E5457A', '#9B4DB5']} style={[s.foodBarFill, { width: `${food.pct}%` }]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} />
                </View>
              </View>
              <Text style={s.foodFreq}>{food.freq}×</Text>
            </View>
          ))}
        </View>

        <View style={[s.card, { gap: 8 }]}>
          <Text style={s.cardTitle}>Symptoms This {period}</Text>
          <View style={s.badgeRow}>
            {symptoms.map((sym, i) => {
              const st = BADGE_STYLES[sym.type] || BADGE_STYLES.pink;
              return (
                <View key={i} style={[s.badge, { backgroundColor: st.bg }]}>
                  <Text style={[s.badgeTxt, { color: st.color }]}>{sym.label}</Text>
                </View>
              );
            })}
          </View>
        </View>

        <View style={s.card}>
          <Text style={s.cardTitle}>Next {period === 'Weekly' ? 'Week' : 'Month'} Tip</Text>
          <Text style={s.tipTxt}>{nextWeekTip}</Text>
        </View>

        <View style={s.actionRow}>
          <TouchableOpacity style={s.primaryBtn} onPress={handleDownload} activeOpacity={0.85} disabled={exporting}>
            <LinearGradient colors={['#E5457A', '#9B4DB5']} style={s.primaryGrad} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
              {exporting ? <ActivityIndicator color="#fff" /> : <Text style={s.primaryTxt}>⬇ Download PDF</Text>}
            </LinearGradient>
          </TouchableOpacity>
          <TouchableOpacity style={s.ghostBtn} onPress={handleShare} disabled={exporting}>
            <Text style={s.ghostTxt}>Share</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  header: { flexDirection: 'row', alignItems: 'center', padding: 16, paddingHorizontal: 20, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border, gap: 12 },
  backBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.lavender, alignItems: 'center', justifyContent: 'center' },
  backArrow: { fontSize: 22, color: colors.purple, fontWeight: '700' },
  headerTitle: { flex: 1, fontSize: 17, fontWeight: '800', color: colors.textPrimary },
  scroll: { padding: 16, gap: 16 },
  tabToggle: { flexDirection: 'row', backgroundColor: colors.lavender, borderRadius: 16, padding: 4 },
  tabBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center' },
  tabBtnActive: { backgroundColor: colors.surface },
  tabTxt: { fontSize: 12, fontWeight: '800', color: colors.textSecondary },
  tabTxtActive: { color: colors.purple },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statCell: { flex: 1, minWidth: '45%', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 16 },
  statVal: { fontSize: 24, fontWeight: '900', color: colors.textPrimary },
  statLabel: { fontSize: 11, color: colors.textSecondary, marginTop: 2, fontWeight: '600' },
  card: { backgroundColor: colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: colors.border },
  cardTitle: { fontSize: 11, fontWeight: '800', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12 },
  emptyTxt: { fontSize: 12, color: colors.textSecondary, textAlign: 'center', paddingVertical: 8 },
  foodRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 },
  foodName: { fontSize: 12, fontWeight: '700', color: colors.textPrimary },
  foodBarTrack: { height: 4, backgroundColor: colors.border, borderRadius: 99, overflow: 'hidden' },
  foodBarFill: { height: '100%', borderRadius: 99 },
  foodFreq: { fontSize: 11, color: colors.textSecondary, fontWeight: '700', width: 24, textAlign: 'right' },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 99 },
  badgeTxt: { fontSize: 11, fontWeight: '700' },
  tipTxt: { fontSize: 13, color: colors.textPrimary, lineHeight: 20 },
  actionRow: { flexDirection: 'row', gap: 8 },
  primaryBtn: { flex: 1, borderRadius: 16, overflow: 'hidden', shadowColor: '#E5457A', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.35, shadowRadius: 24, elevation: 8 },
  primaryGrad: { paddingVertical: 14, alignItems: 'center', borderRadius: 16 },
  primaryTxt: { color: '#fff', fontSize: 14, fontWeight: '700' },
  ghostBtn: { flex: 1, paddingVertical: 14, alignItems: 'center', borderRadius: 16, borderWidth: 1.5, borderColor: colors.border },
  ghostTxt: { fontSize: 14, fontWeight: '700', color: colors.purple },
});